"""Real, sourced 2026 fantasy football draft-strategy notes, hand-collected.

Not ESPN player news (injuries, transactions) — this is specifically
draft-strategy content: sleeper calls, bust warnings, and value picks from
actual fantasy analysts, gathered 2026-08-30 via live web search against
sites like ESPN, RotoBaller, RotoWire, DraftSharks, NFL.com and Roto Street
Journal.

Every entry here is a REAL claim from a REAL, dated article, matched by name
against players who exist in data/projections.csv. Players quoted in an
article who are not in our pool (mostly deep-roster or rookie names our
projection set does not carry) are left out rather than guessed at.

This file is a snapshot, not a live feed — there's no way to re-run the
search from inside the Flask app itself, so it goes stale the way any
hand-collected reference does. Re-run the searches and refresh this file
before each new season if it's still in use.
"""

# kind: "top12" (first-round strategy), "bust" (fade warning),
#       "sleeper" (late-round value), "undervalued" (mid-round value)
DRAFT_TIPS = [
    # ── Top-12 strategy (Roto Street Journal, "The Wolf's Top-12 Picks", 2026-08-27) ──
    {"name": "Jahmyr Gibbs", "kind": "top12",
     "note": "Elite talent with untapped upside, entering peak years with increased volume after Montgomery's departure.",
     "source": "Roto Street Journal", "url": "https://www.rotostreetjournal.com/2026/08/27/who-should-you-draft-in-the-first-round-of-fantasy-football-in-2026-the-wolfs-top-12-picks/"},
    {"name": "Bijan Robinson", "kind": "top12",
     "note": "Consistent elite production with the highest touch efficiency and significant remaining touchdown upside.",
     "source": "Roto Street Journal", "url": "https://www.rotostreetjournal.com/2026/08/27/who-should-you-draft-in-the-first-round-of-fantasy-football-in-2026-the-wolfs-top-12-picks/"},
    {"name": "Puka Nacua", "kind": "top12",
     "note": "League-leading target rate and yards per route run with a dominant role in the McVay offense.",
     "source": "Roto Street Journal", "url": "https://www.rotostreetjournal.com/2026/08/27/who-should-you-draft-in-the-first-round-of-fantasy-football-in-2026-the-wolfs-top-12-picks/"},
    {"name": "Ja'Marr Chase", "kind": "top12",
     "note": "Elite week-winning upside with a stable floor, though slightly lower consistency than Puka Nacua.",
     "source": "Roto Street Journal", "url": "https://www.rotostreetjournal.com/2026/08/27/who-should-you-draft-in-the-first-round-of-fantasy-football-in-2026-the-wolfs-top-12-picks/"},
    {"name": "Jaxon Smith-Njigba", "kind": "top12",
     "note": "Historic receiving-yards leader who dominated with a concentrated target share in a run-heavy offense.",
     "source": "Roto Street Journal", "url": "https://www.rotostreetjournal.com/2026/08/27/who-should-you-draft-in-the-first-round-of-fantasy-football-in-2026-the-wolfs-top-12-picks/"},
    {"name": "Amon-Ra St. Brown", "kind": "top12",
     "note": "The safest pick at the position: elite durability, consistent top-3 finishes, and chemistry with Goff.",
     "source": "Roto Street Journal", "url": "https://www.rotostreetjournal.com/2026/08/27/who-should-you-draft-in-the-first-round-of-fantasy-football-in-2026-the-wolfs-top-12-picks/"},
    {"name": "James Cook III", "kind": "top12",
     "note": "Rushing crown winner with elite touchdown upside and potential for an expanded receiving role.",
     "source": "Roto Street Journal", "url": "https://www.rotostreetjournal.com/2026/08/27/who-should-you-draft-in-the-first-round-of-fantasy-football-in-2026-the-wolfs-top-12-picks/"},
    {"name": "Jonathan Taylor", "kind": "top12",
     "note": "Pace-setting performer through ten weeks before a quarterback injury derailed late-season production.",
     "source": "Roto Street Journal", "url": "https://www.rotostreetjournal.com/2026/08/27/who-should-you-draft-in-the-first-round-of-fantasy-football-in-2026-the-wolfs-top-12-picks/"},
    {"name": "Christian McCaffrey", "kind": "top12",
     "note": "Historic scoring seasons, but age, mileage and the history of regression after 400+ touch seasons are real risks.",
     "source": "Roto Street Journal", "url": "https://www.rotostreetjournal.com/2026/08/27/who-should-you-draft-in-the-first-round-of-fantasy-football-in-2026-the-wolfs-top-12-picks/"},
    {"name": "Kenneth Walker III", "kind": "top12",
     "note": "Explosive talent entering an elite offensive scheme with light box looks and untapped pass-catching potential.",
     "source": "Roto Street Journal", "url": "https://www.rotostreetjournal.com/2026/08/27/who-should-you-draft-in-the-first-round-of-fantasy-football-in-2026-the-wolfs-top-12-picks/"},
    {"name": "Chase Brown", "kind": "top12",
     "note": "Three-down weapon averaging 20.9 points per game alongside Burrow, with elite red-zone involvement.",
     "source": "Roto Street Journal", "url": "https://www.rotostreetjournal.com/2026/08/27/who-should-you-draft-in-the-first-round-of-fantasy-football-in-2026-the-wolfs-top-12-picks/"},

    # ── Busts / fades (RotoWire, "2026 Fantasy Football Busts: 32 Teams, 32 Busts") ──
    {"name": "De'Von Achane", "kind": "bust",
     "note": "Mike McDaniel's departure, Jaylen Waddle's trade, and Malik Willis's uncertainty complicate his situation.",
     "source": "RotoWire", "url": "https://www.rotowire.com/football/article/2026-fantasy-football-busts-32-teams-32-busts-127643"},
    {"name": "Tee Higgins", "kind": "bust",
     "note": "Injury history (12 missed games in three years, two concussions) combined with Joe Burrow's own availability concerns.",
     "source": "RotoWire", "url": "https://www.rotowire.com/football/article/2026-fantasy-football-busts-32-teams-32-busts-127643"},
    {"name": "Bucky Irving", "kind": "bust",
     "note": "Final six games of 2025 showed declining efficiency, and Kenny Gainwell's role threatens his passing-down work.",
     "source": "RotoWire", "url": "https://www.rotowire.com/football/article/2026-fantasy-football-busts-32-teams-32-busts-127643"},
    {"name": "Garrett Wilson", "kind": "bust",
     "note": "Ranks 70th in fantasy points per target among qualified receivers despite high target volume.",
     "source": "NFL.com", "url": "https://www.nfl.com/news/2026-nfl-fantasy-football-10-overvalued-undervalued-nfl-players-to-know-before-you-draft"},
    {"name": "Jayden Daniels", "kind": "bust",
     "note": "Missed 10 games with injury trends worsening, and a scheme shift toward under-center concepts may not suit him.",
     "source": "RotoWire", "url": "https://www.rotowire.com/football/article/2026-fantasy-football-busts-32-teams-32-busts-127643"},
    {"name": "TreVeyon Henderson", "kind": "bust",
     "note": "Poor pass protection cost him snaps late in the season, and Rhamondre Stevenson has reclaimed the lead role.",
     "source": "RotoWire", "url": "https://www.rotowire.com/football/article/2026-fantasy-football-busts-32-teams-32-busts-127643"},
    {"name": "Jalen Hurts", "kind": "bust",
     "note": "Rushing volume has declined three straight years, and losing A.J. Brown removes his best deep threat.",
     "source": "RotoWire", "url": "https://www.rotowire.com/football/article/2026-fantasy-football-busts-32-teams-32-busts-127643"},
    {"name": "David Montgomery", "kind": "bust",
     "note": "At 29 with extensive career carries, he's approaching the historical running-back decline threshold.",
     "source": "NFL.com", "url": "https://www.nfl.com/news/2026-nfl-fantasy-football-10-overvalued-undervalued-nfl-players-to-know-before-you-draft"},
    {"name": "Jameson Williams", "kind": "bust",
     "note": "His 2025 production required either Sam LaPorta's absence or inflated game scripts from defensive collapses.",
     "source": "RotoWire", "url": "https://www.rotowire.com/football/article/2026-fantasy-football-busts-32-teams-32-busts-127643"},
    {"name": "Courtland Sutton", "kind": "bust",
     "note": "Jaylen Waddle's arrival compresses his target share, and he's turning 31 this season.",
     "source": "RotoWire", "url": "https://www.rotowire.com/football/article/2026-fantasy-football-busts-32-teams-32-busts-127643"},
    {"name": "Jauan Jennings", "kind": "bust",
     "note": "Kevin O'Connell's offense values him as a blocker, capping his snaps and target upside behind Jordan Addison.",
     "source": "RotoWire", "url": "https://www.rotowire.com/football/article/2026-fantasy-football-busts-32-teams-32-busts-127643"},
    {"name": "Khalil Shakir", "kind": "bust",
     "note": "Snap rate fell from 76% to 57%, and DJ Moore's arrival further compresses his target opportunities.",
     "source": "RotoWire", "url": "https://www.rotowire.com/football/article/2026-fantasy-football-busts-32-teams-32-busts-127643"},
    {"name": "Rico Dowdle", "kind": "bust",
     "note": "Efficiency collapsed in the second half of 2025, and Jaylen Warren projects for more touches in Pittsburgh.",
     "source": "RotoWire", "url": "https://www.rotowire.com/football/article/2026-fantasy-football-busts-32-teams-32-busts-127643"},
    {"name": "Kyle Pitts Sr.", "kind": "bust",
     "note": "His strong per-game average was inflated by Drake London's absence and one massive Week 15 explosion.",
     "source": "RotoWire", "url": "https://www.rotowire.com/football/article/2026-fantasy-football-busts-32-teams-32-busts-127643"},
    {"name": "Dallas Goedert", "kind": "bust",
     "note": "11 touchdowns last season represented unsustainable production at roughly 2x his career touchdown rate.",
     "source": "NFL.com", "url": "https://www.nfl.com/news/2026-nfl-fantasy-football-10-overvalued-undervalued-nfl-players-to-know-before-you-draft"},
    {"name": "Michael Wilson", "kind": "bust",
     "note": "New coach Mike LaFleur is expected to swap the vertical passing attack for catch-and-run concepts.",
     "source": "RotoWire", "url": "https://www.rotowire.com/football/article/2026-fantasy-football-busts-32-teams-32-busts-127643"},
    {"name": "Harold Fannin Jr.", "kind": "bust",
     "note": "2025 stats were boosted by David Njoku's injury; Cleveland's offensive upgrades will normalize his usage.",
     "source": "RotoWire", "url": "https://www.rotowire.com/football/article/2026-fantasy-football-busts-32-teams-32-busts-127643"},
    {"name": "Wan'Dale Robinson", "kind": "bust",
     "note": "His 2025 spike required Malik Nabers' injury; with a healthy Nabers and Carnell Tate added, regression is likely.",
     "source": "RotoWire", "url": "https://www.rotowire.com/football/article/2026-fantasy-football-busts-32-teams-32-busts-127643"},
    {"name": "Rashee Rice", "kind": "bust",
     "note": "Only one fully healthy season on his resume, with multiple injuries and potential declining effectiveness.",
     "source": "RotoWire", "url": "https://www.rotowire.com/football/article/2026-fantasy-football-busts-32-teams-32-busts-127643"},
    {"name": "Alec Pierce", "kind": "bust",
     "note": "Ankle recovery complications with no clear return timeline, and backup QB play threatens his deep-ball role.",
     "source": "RotoWire", "url": "https://www.rotowire.com/football/article/2026-fantasy-football-busts-32-teams-32-busts-127643"},
    {"name": "Tre Tucker", "kind": "bust",
     "note": "2025 line was propped up by the Jakobi Meyers trade and one dominant Week 3 performance.",
     "source": "RotoWire", "url": "https://www.rotowire.com/football/article/2026-fantasy-football-busts-32-teams-32-busts-127643"},
    {"name": "Bhayshul Tuten", "kind": "bust",
     "note": "Bottom 2% in explosive run rate leaguewide, with no clearly defined role in Jacksonville's backfield.",
     "source": "RotoWire", "url": "https://www.rotowire.com/football/article/2026-fantasy-football-busts-32-teams-32-busts-127643"},
    {"name": "Matthew Golden", "kind": "bust",
     "note": "Despite first-round draft capital and elite speed, he produced just 29 catches and zero TDs in 14 games as a rookie.",
     "source": "RotoWire", "url": "https://www.rotowire.com/football/article/2026-fantasy-football-busts-32-teams-32-busts-127643"},
    {"name": "Jaxson Dart", "kind": "bust",
     "note": "Threw just 15 TDs in 12 starts, lacks receiving safety nets, and faces a new offensive system.",
     "source": "RotoWire", "url": "https://www.rotowire.com/football/article/2026-fantasy-football-busts-32-teams-32-busts-127643"},

    # ── Undervalued (NFL.com, "10 overvalued, undervalued players") ──
    {"name": "Malik Nabers", "kind": "undervalued",
     "note": "Expected to avoid the PUP list; averaged 18.24 fantasy points per game when healthy in 2025.",
     "source": "NFL.com", "url": "https://www.nfl.com/news/2026-nfl-fantasy-football-10-overvalued-undervalued-nfl-players-to-know-before-you-draft"},
    {"name": "Rhamondre Stevenson", "kind": "undervalued",
     "note": "Averaged 17.1 fantasy points per game over his final eight contests after reclaiming the starting role.",
     "source": "NFL.com", "url": "https://www.nfl.com/news/2026-nfl-fantasy-football-10-overvalued-undervalued-nfl-players-to-know-before-you-draft"},
    {"name": "Zay Flowers", "kind": "undervalued",
     "note": "Finished sixth in receiving yards with an elite 2.5 yards per route run last season.",
     "source": "NFL.com", "url": "https://www.nfl.com/news/2026-nfl-fantasy-football-10-overvalued-undervalued-nfl-players-to-know-before-you-draft"},
    {"name": "Jake Ferguson", "kind": "undervalued",
     "note": "Finished as TE5 last year and could have finished TE3 overall if not for a late-season injury.",
     "source": "NFL.com", "url": "https://www.nfl.com/news/2026-nfl-fantasy-football-10-overvalued-undervalued-nfl-players-to-know-before-you-draft"},

    # ── Sleepers (DraftSharks, "Fantasy Football Sleepers 2026") ──
    {"name": "Kyler Murray", "kind": "sleeper",
     "note": "QB18 ADP despite legitimate top-6 upside thanks to his situation and rushing ability.",
     "source": "DraftSharks", "url": "https://www.draftsharks.com/article/fantasy-football-sleepers"},
    {"name": "Tyler Shough", "kind": "sleeper",
     "note": "Delivered QB12 per-game fantasy production as a rookie, with room for growth under Kellen Moore in year two.",
     "source": "DraftSharks", "url": "https://www.draftsharks.com/article/fantasy-football-sleepers"},
    {"name": "Jordan Mason", "kind": "sleeper",
     "note": "Outperformed Aaron Jones on efficiency metrics and is positioned for an increased workload.",
     "source": "DraftSharks", "url": "https://www.draftsharks.com/article/fantasy-football-sleepers"},
    {"name": "Rashid Shaheed", "kind": "sleeper",
     "note": "A mid-season trade depressed his stats; Seattle's extension signals a long-term investment and real opportunity.",
     "source": "DraftSharks", "url": "https://www.draftsharks.com/article/fantasy-football-sleepers"},
    {"name": "Jalen McMillan", "kind": "sleeper",
     "note": "Flashed eight touchdowns as a rookie before injury; positioned to benefit from Mike Evans' eventual absence.",
     "source": "DraftSharks", "url": "https://www.draftsharks.com/article/fantasy-football-sleepers"},
    {"name": "Dalton Kincaid", "kind": "sleeper",
     "note": "Led all tight ends in yards per route run (2.79) despite limited playing time due to injuries.",
     "source": "DraftSharks", "url": "https://www.draftsharks.com/article/fantasy-football-sleepers"},
    {"name": "Isaiah Likely", "kind": "sleeper",
     "note": "Efficient pass-catcher who was hidden behind Mark Andrews; a new opportunity gives him a real path to volume.",
     "source": "DraftSharks", "url": "https://www.draftsharks.com/article/fantasy-football-sleepers"},
    {"name": "Adonai Mitchell", "kind": "sleeper",
     "note": "Target earner who saw 80%+ snap rate usage after his trade, with an improved 2026 situation.",
     "source": "DraftSharks", "url": "https://www.draftsharks.com/article/fantasy-football-sleepers"},
]
